### PR TITLE
chore: add noUnusedParameters TS rule

### PR DESCRIPTION
**Pull request by 0xApotheosis**
## Description

Add `noUnusedParameters` TS rule.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

N/A

## Risk

N/A

## Testing

N/A

## Screenshots (if applicable)

N/A

### CODE REVIEW

**Review by gomesalexandre — APPROVED** [review]
LGTM
Tried removing the `@ts-ignore` directives and I'm properly getting compiler violations reported:
```shell
➜  shapeshiftLib git:(enforce-noUnusedParameters) ✗ yarn type-check
yarn run v1.22.17
$ lerna run type-check
lerna notice cli v4.0.0
lerna info versioning independent
lerna info Executing command in 7 packages: "yarn run type-check"
lerna info run Ran npm script 'type-check' in '@shapeshiftoss/errors' in 1.0s:
$ tsc --project ./tsconfig.json --noEmit
lerna info run Ran npm script 'type-check' in '@shapeshiftoss/types' in 1.1s:
$ tsc --project ./tsconfig.build.json --noEmit
lerna info run Ran npm script 'type-check' in '@shapeshiftoss/caip' in 1.3s:
$ tsc --project ./tsconfig.build.json --noEmit
lerna info run Ran npm script 'type-check' in '@shapeshiftoss/market-service' in 1.3s:
$ tsc --project ./tsconfig.build.json --noEmit
lerna ERR! yarn run type-check exited 2 in '@shapeshiftoss/chain-adapters'
lerna ERR! yarn run type-check stdout:
$ tsc --project ./tsconfig.build.json --noEmit
src/bitcoin/BitcoinChainAdapter.ts:71:5 - error TS6133: 'input' is declared but its value is never read.

71     input: chainAdapters.TxHistoryInput // eslint-disable-line @typescript-eslint/no-unused-vars
       ~~~~~


Found 1 error in src/bitcoin/BitcoinChainAdapter.ts:71

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run type-check stderr:
error Command failed with exit code 2.
lerna ERR! yarn run type-check exited 2 in '@shapeshiftoss/chain-adapters'
```

**Comment by 0xApotheosis** [comment]
> I am wondering if we need this as an eslint rule when we already have the tsc rule enabled? We can probably remove one or the other. As eslint wouldn't be able to fix this automatically, I don't see the benefit of adding it to eslint rules

I'm not sure I follow - this PR _is_ adding a TSC rule, not eslint.

**Comment by kaladinlight** [comment]
> > I am wondering if we need this as an eslint rule when we already have the tsc rule enabled? We can probably remove one or the other. As eslint wouldn't be able to fix this automatically, I don't see the benefit of adding it to eslint rules
> 
> I'm not sure I follow - this PR _is_ adding a TSC rule, not eslint.

You are right, not sure why I was thinking it was eslint. I got confused about the need for multiple ignore comments, but one is coming from no unused var and one from no used args. These don't directly conflict technically I suppose. In the other PR though, wouldn't the noUnusedLocal and no-unused-vars be redundant? Point being it just seems like we have rules in both tsc and eslint and want to make sure they don't conflict or are redundant (requiring two ignore comments for the same thing)

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xApotheosis** [comment]
> > > I am wondering if we need this as an eslint rule when we already have the tsc rule enabled? We can probably remove one or the other. As eslint wouldn't be able to fix this automatically, I don't see the benefit of adding it to eslint rules
> > 
> > 
> > I'm not sure I follow - this PR _is_ adding a TSC rule, not eslint.
> 
> You are right, not sure why I was thinking it was eslint. I got confused about the need for multiple ignore comments, but one is coming from no unused var and one from no used args. These don't directly conflict technically I suppose. In the other PR though, wouldn't the noUnusedLocal and no-unused-vars be redundant? Point being it just seems like we have rules in both tsc and eslint and want to make sure they don't conflict or are redundant (requiring two ignore comments for the same thing)

For posterity on this, I _think_ the TSC rule is a superset of the ESLint one, as it has a greater ability to detect code issues. Not high priority, but if I can confirm that assertion is true I'll remove the ESLint one, as you're right @kaladinlight, having to add comments to ignore both rules is silly.

**Pull request merged**
