### PR TITLE
chore: add asset description for crvCVXETH

### PR DESCRIPTION
**Pull request by krissnawat**

### CODE REVIEW

**Review by willyogo — CHANGES_REQUESTED** [review]
Looks great @krissnawat! Just have a few requests: can you please add links to the shapeshift asset pages for the underlying assets? 

ie. [CVX](https://app.shapeshift.com/assets/eip155:1/erc20:0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b)

Also, can you link ShapeShift to the earn page? 

ie. [ShapeShift](https://app.shapeshift.com/defi/earn)

(see https://github.com/shapeshift/lib/pull/424/files as an example)

Last thing: next time you submit one of these, can you post a link to the PR in the #product-design-public channel in discord.gg/shapeshift (add the product role in #role-selector if you can't access it)?

Thanks for picking up this bounty; hope you take on more!

**Comment by krissnawat** [comment]
> Looks great @krissnawat! Just have a few requests: can you please add links to the shapeshift asset pages for the underlying assets?
> 
> ie. [CVX](https://app.shapeshift.com/assets/eip155:1/erc20:0x4e3fbd56cd56c3e72c1403e103b45db9da5b9d2b)
> 
> Also, can you link ShapeShift to the earn page?
> 
> ie. [ShapeShift](https://app.shapeshift.com/defi/earn)
> 
> (see https://github.com/shapeshift/lib/pull/424/files as an example)
> 
> Last thing: next time you submit one of these, can you post a link to the PR in the #product-design-public channel in discord.gg/shapeshift (add the product role in #role-selector if you can't access it)?
> 
> Thanks for picking up this bounty; hope you take on more!

done

**Review by willyogo — APPROVED** [review]
looks great! thanks for making the changes

**Review by 0xApotheosis — APPROVED** [review]

**Review by 0xdef1cafe — CHANGES_REQUESTED** [review]
hey @krissnawat please see my comment on the other PR as it relates to this one too

https://github.com/shapeshift/lib/pull/436#pullrequestreview-910944814

**Comment by krissnawat** [comment]
> hey @krissnawat please see my comment on the other PR as it relates to this one too
> 
> [#436 (review)](https://github.com/shapeshift/lib/pull/436#pullrequestreview-910944814)

all my pr done

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
@krissnawat looks good but please rebase off of main

**Pull request merged**
