### PR TITLE
chore: add asset descriptions 3Crypto, crvCVXCRV, crvEURS, crv3EUR

### PR DESCRIPTION
**Pull request by Jeustie**
add asset descriptions for 3Crypto, crvCVXCRV, crvEURS, crv3EUR

### CODE REVIEW

**Comment by 0xdef1cafe** [comment]
hey @Jeustie can you please fix conflicts?

**Comment by 0xdef1cafe** [comment]
@Jeustie you're also failing CI

**Comment by decentralized-j** [comment]
fyi @gomesalexandre @0xdef1cafe - this has a green light from product once engineering items are resolved. ty sers

**Review by cjthompson — APPROVED** [review]

**Comment by Jeustie** [comment]
I think that i resolved the conflicts

**Review by gomesalexandre — APPROVED** [review]

**Pull request merged**
