### PR TITLE
feat: chain and asset utility functions

### PR DESCRIPTION
**Pull request by DaoDev44**
- Add `getFeeAssetIdFromAssetId` and `chainIdToFeeAssetId` to utils of CAIP package.
- Moving [this](https://github.com/shapeshift/web/blob/develop/src/state/slices/portfolioSlice/utils.ts#L39) logic from web to lib.

### CODE REVIEW

**Review by elmutt — DISMISSED** [review]

**Review by theoboldfrazier — DISMISSED** [review]

**Review by elmutt — APPROVED** [review]

**Review by theoboldfrazier — APPROVED** [review]
Looks good.

**Review by elmutt — DISMISSED** [review]

**Review by cjthompson — CHANGES_REQUESTED** [review]
make a PR with only the caip changes and a second PR for the swapper change

**Comment by DaoDev44** [comment]
@cjthompson Please have a look at #665 (CAIP changes). After that is merged, I'll merge main back into this branch and update this PR with the correct CAIP version.

**Comment by gomesalexandre** [comment]
> @cjthompson Please have a look at #665 (CAIP changes). After that is merged, I'll merge main back into this branch and update this PR with the correct CAIP version.

In the meantime, you can use `add-web-utils` as a destination branch (it will automatically change to develop when the PR's merged and the branch deleted) to have a clean diff

**Comment by elmutt** [comment]
> make a PR with only the caip changes and a second PR for the swapper change

This is done

**Review by cjthompson — APPROVED** [review]

**Review by elmutt — APPROVED** [review]

**Pull request merged**
