### PR TITLE
fix: support all litecoin account types

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
**do not merge until verified this is working with demo wallet locally - i have some weird nondeterministic bug locally. it works with actual wallets**

* this was erroneously missed when testing LTC
* this adds segwit and segwit native support for LTC

image

### CODE REVIEW

**Review by kaladinlight — APPROVED** [review]

**Review by 0xApotheosis — DISMISSED** [review]
I've tried two different machines and am getting the below error on both when loading demo wallet, same as @0xdef1cafe:

Screen Shot 2022-08-12 at 9 24 51 am

Putting "request changes" on this until we work out what's up.

**Comment by gomesalexandre** [comment]
> I've tried two different machines and am getting the below error on both when loading demo wallet, same as @0xdef1cafe:
> 
> Screen Shot 2022-08-12 at 9 24 51 am
> 
> Putting "request changes" on this until we work out what's up.

Same here:

image

**Comment by kaladinlight** [comment]
https://github.com/shapeshift/web/pull/2423 fixes the issue, as soon as that goes in, we are good to merge this

**Review by gomesalexandre — APPROVED** [review]
Tested working while linked in https://github.com/shapeshift/web/pull/2423, let's get this one in so we can bump it in the web PR directly

**Pull request merged**
