### PR TITLE
feat(types): export Asset type from asset-service

### PR DESCRIPTION
**Pull request by gomesalexandre**
BREAKING CHANGE: Asset is now exported from asset-service, and all consumers should now import it from it

### Description

This moves the Asset type export to asset-service, allowing us to use the `AssetId` / `ChainId` types for the `assetId` and `chainId` properties of `Asset` without any circular dependencies.

It should give us more confidence in web typings e.g accessors that should be of type `AssetId` or `ChainId`

### CODE REVIEW

**Comment by kaladinlight** [comment]
This creates a circular dependency between caip and types. More accurate fix would be moving the asset service types out into the asset service package and then they could utilize the caip types there

**Comment by gomesalexandre** [comment]
> This creates a circular dependency between caip and types. More accurate fix would be moving the asset service types out into the asset service package and then they could utilize the caip types there

That sounds good 👍🏽 less reliance on the types package, and more types living where they really should i.e in their domain package. Moved this to draft for now

**Review by kaladinlight — DISMISSED** [review]
there is a new conflict, but this update looks good to me

**Comment by gomesalexandre** [comment]
> there is a new conflict, but this update looks good to me

Mergefixed! Also ran `local-ci` as a sanity check which is very happy locally

**Comment by gomesalexandre** [comment]
Unrugged conflicts again

**Review by kaladinlight — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Review by elmutt — APPROVED** [review]

**Pull request merged**
