### PR TITLE
feat(swapper): propagate usd/crypto human/precision vernacular

### PR DESCRIPTION
**Pull request by gomesalexandre**
### Description

This PR propagates the new USD/crypto human/precision vernacular introduced in https://github.com/shapeshift/lib/pull/1043 across swapper

### CODE REVIEW

**Comment by gomesalexandre** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1052** <a href="https://app.graphite.dev/github/pr/shapeshift/lib/1052" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/shapeshift/lib/1052?utm_source=stack-comment).

**Comment by 0xdef1cafe** [comment]
probably need associated web PR?

**Comment by gomesalexandre** [comment]
> probably need associated web PR?

Here she is https://github.com/shapeshift/web/pull/3122

**Review by 0xApotheosis — APPROVED** [review]
Looks very sane to me, nice refactor.

Confirmed that this works with https://github.com/shapeshift/web/pull/3122.

**Pull request merged**
