### PR TITLE
style: bump prettier and enforce its formatting

### PR DESCRIPTION
**Pull request by reidrankin**
The `prettier` version we use is old and doesn't support `import type`. We've also been using eslint with the prettier plugin, but not prettier itself, so there's various formatting things that have slipped through that prettier doesn't like.

This bumps prettier (and unlocks its version), reformats everything (`yarn prettier -w .`), and adds an explicit prettier check to the lint step.

### CODE REVIEW

**Comment by cjthompson** [comment]
Did you make any other changes besides the automatic linting? I can't look through 70k lines for changes.

**Comment by cjthompson** [comment]
We should have talked about what prettier rules to use. Did you use the same ones from lib and web?

**Comment by reidrankin** [comment]
I didn't add or remove any rules; this just just:
- bumps all the already-installed prettier package versions
- run `yarn prettier -w .`
- stuck explicit prettier runs into the lint commands in package.json

**Comment by 0xdef1cafe** [comment]
> I didn't add or remove any rules; this just:
> 
> * bumps all the already-installed prettier package versions
> * run `yarn prettier -w .`
> * stuck explicit prettier runs into the lint commands in package.json

this should be configured as a plugin for eslint it integrates with IDE's in one step and becomes a one step build failure.

**Comment by 0xdef1cafe** [comment]
also, you'll need to coordinate with anyone that has branches in progress that aren't already open as PRs, as this is the worlds nastiest merge conflict to fix.

**Pull request closed without merging**
