### PR TITLE
chore: rename BIP32Params to BIP44Params

### LINKED ISSUE #132: Rename BIP32Params to BIP44Params
MrNerdHair convinced us this is correct so make the change now before it's called this everywhere

### PR DESCRIPTION
**Pull request by jdambron**
## Description

Rename `BIP32Params` to `BIP44Params`

⚠️ Impact on web, dedicated PR coming. 

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [x] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #132

### CODE REVIEW

**Comment by jdambron** [comment]
PR on web [https://github.com/shapeshift/web/pull/567](https://github.com/shapeshift/web/pull/567)

**Comment by 0xean** [comment]
@jdambron - thanks again for the PR!

I think there may be a few things left to refactor here.

1. lib/packages/chain-adapters/src/utils/bip32.ts file should be renamed
2. lib/packages/chain-adapters/src/bip32.test.ts file should be renamed
3. lib/packages/chain-adapters/src/utils/index.ts update the export for the new file name

@reidrankin - it looks like we need a similiar ticket in hdwallet-core for `bip32ToAddressNList`, can you confirm?

**Comment by jdambron** [comment]
@0xean renaming of the files :heavy_check_mark:

**Review by reidrankin — APPROVED** [review]

**Review by 0xean — APPROVED** [review]

**Comment by cjthompson** [comment]
We need to be careful here because this is a backwards incompatible change. The obvious solution would be to do a major version bump on the package.

**Review by natven — APPROVED** [review]
This looks great! Thank you!

**Pull request merged**
